name: "Format and Publish"
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "index.*"
      - "!index.min.css"

jobs:
  setup-env:
    name: "Setup Environment"
    runs-on: ubuntu-latest
    steps:
      - 
        id: setup-node
        name: "Setup Node 16.x"
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

  cache-and-install:
    name: "Install + Cache Modules"
    runs-on: ubuntu-latest
    needs: [setup-env]
    steps:
      build:
        - 
          id: checkout-repo
          needs: [setup-node]
          name: "Checkout Repository"
          uses: actions/checkout@v2
        - 
          id: cache-deps
          needs: [checkout-repo]
          name: "Cache PNPM Modules"
          uses: actions/cache@v2
          with:
            path: ~/.pnpm-store
            key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
            restore-keys: |
              ${{ runner.os }}-
        - 
          id: setup-pnpm
          needs: [cache-deps]
          name: "Setup PNPM"
          uses: pnpm/action-setup@v2.1.0
          with:
            run_install: |
                - recursive: true

        - 
          env:
            GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
            GH_TOKEN: ${{github.token}}
            NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          run: |
            prettier --ignore-path .gitignore --write .
            uglifycss index.css > index.min.css
            GIT_AUTHOR_NAME="Nicholas Berlette" GIT_AUTHOR_EMAIL="nick@berlette.com" GIT_COMMITTER_NAME="Nicholas Berlette" GIT_COMMITTER_EMAIL="nick@berlette.com" git commit -a -m "[chore]: lint and format code"
            npm version patch
            git push -u origin main --follow-tags
        -
          run: |
            echo -e "\n//registry.npmjs.org/:_authToken=${NPM_TOKEN-}\n" >> .npmrc
            echo -e "\n//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN:-$GH_TOKEN}\n" >> .npmrc
            npm publish
            npm publish --ignore-scripts --scope=@nberlette --@nberlette:registry='https://npm.pkg.github.com/'

	-
	  run: rm -f .npmrc

